spring.application.name=ecommerce-backend

spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=7498840092
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.h2.console.enabled=false
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

app.jwt.secret=VGhpc0lzQVNlY3VyZVNlY3JldEtleUZvckpXVFRva2VuR2VuZXJhdGlvbjEyMw==
app.jwt.expiration-ms=86400000

paypal.client.id=AQpMsebEaHbw7Gfwi9hFAl2v0piF4_m9BTnl6BxjVlpK32FE7CNmaNUoqIr6NzT44MZS1h_Mi19sdfGP
paypal.client.secret=EGUGkXtGCWrOFu4etShe9UIJ2Fbh6s8jnPWe5sjbLDp0x_qRhQ7P3eirfLZw9nYp4yhRuZFnvUGQtyV6